### ISSUE TITLE
Diamond Hands Don't Work

### ISSUE THREAD

**Issue by heheWelp** [skylorbeck/MageHand#6]
When placing a Diamond Mage Hand, the item doesn't leave your inventory. When the hand you placed dies, you get a duplicate hand item. On top of this, the hand doesn't seem to point to anything. I may just be using them wrong but I couldn't find anything that shows how they are used. Either way that first glitch seemed enough to make a report about. All the other hands seem to work perfectly, just the diamond ones :(

**Comment by heheWelp** [comment]
I figured out how to make them point, I'm just dumb. They still duplicate though.

**Comment by skylorbeck** [comment]
This bug is not replicatble. If you are using a modpack, please report it to them or update this ticket with the mod that is conflicting

**Comment by skylorbeck** [comment]
Hey, it was an incompatibility with Lithium. Should be fixed in 1.1.3
