### ISSUE TITLE
Incompatibility with Create

### ISSUE THREAD

**Issue by skylorbeck** [skylorbeck/MageHand#8]
I have a similar issue with gold hands, but the crash looks different
"Cannot invoke "net.minecraft.class_1657.method_31548()" because "player" is null"
https://pastebin.pl/view/d4bd99b5

_Originally posted by @Sebas-Re in https://github.com/skylorbeck/MageHand/issues/7#issuecomment-1151765960_

**Comment by skylorbeck** [comment]
This is caused by com.simibubi.create.content.curiosities.symmetry.SymmetryHandler.onBlockPlaced(SymmetryHandler.java:57) whatever that is

**Comment by Sebas-Re** [comment]
Ooohhh ok thanks you! So weird that thing corrupted the poor hand

**Comment by skylorbeck** [comment]
> Ooohhh ok thanks you! So weird that thing corrupted the poor hand 

What is that mod, by the way?

**Comment by Sebas-Re** [comment]
It's Create. Very likely the wand of symmetry, although the player that reported this on our discord said they don't have it so not sure why is doing it, I'll have to ask Create Devs about it

**Comment by skylorbeck** [comment]
Fixed as of [Create#410](https://github.com/Fabricators-of-Create/Create/issues/410)

**Comment by skylorbeck** [comment]
https://github.com/Fabricators-of-Create/Create/issues/410#issuecomment-1413140526

They won't be fixing it. You have to either drop my mod or theirs. I understand if you choose mine.
